spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri:  mongodb://localhost:27017/fitnessactivity
      database: fitnessactivity
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

