spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: root
    password: Sujith@1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka